image:
  repository: nelssec/qualys-agent-bootstrapper
  tag: latest
  pullPolicy: IfNotPresent

namespace: qualys

env:
  activationIdSecret: qualys-agent-credentials
  customerIdSecret: qualys-agent-credentials
  configMap: qualys-agent-config

volumeMountPath: /host
hostPath: /tmp/install


secrets:
  activationId: ""
  customerId: ""

config:
  serverUri: "https://agent.example.com"
  logLevel: "INFO"
