image:
  repository: nelssec/qualys-agent-bootstrapper
  tag: latest
  pullPolicy: Always

namespace: qualys

env:
  activationIdSecret: qualys-agent-credentials
  customerIdSecret: qualys-agent-credentials
  configMap: qualys-agent-config

volumeMountPath: /host

secrets:
  activationId: ""
  customerId: ""

config:
  serverUri: "https://your.qualys.uri"
  logLevel: "INFO"
