apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.configMap }}
  namespace: {{ .Values.namespace }}
data:
  SERVER_URI: {{ .Values.config.serverUri | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
