apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qualys-cloud-agent
  namespace: {{ .Values.namespace }}
  labels:
    app: qualys-cloud-agent
spec:
  selector:
    matchLabels:
      app: qualys-cloud-agent
  template:
    metadata:
      labels:
        app: qualys-cloud-agent
    spec:
      hostPID: true
      containers:
        - name: qualys-cloud-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: ACTIVATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.activationIdSecret }}
                  key: ACTIVATION_ID
            - name: CUSTOMER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.customerIdSecret }}
                  key: CUSTOMER_ID
            - name: SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMap }}
                  key: SERVER_URI
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMap }}
                  key: LOG_LEVEL
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: host-mount
              mountPath: {{ .Values.volumeMountPath }}
      volumes:
        - name: host-mount
          hostPath:
            path: {{ .Values.hostPath }}
