apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.activationIdSecret }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ACTIVATION_ID: {{ .Values.secrets.activationId | quote }}
  CUSTOMER_ID: {{ .Values.secrets.customerId | quote }}
