apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qualys-cloud-agent
  namespace: {{ .Values.namespace }}
  labels:
    app: qualys-cloud-agent
spec:
  selector:
    matchLabels:
      app: qualys-cloud-agent
  template:
    metadata:
      labels:
        app: qualys-cloud-agent
    spec:
      serviceAccountName: qualys-agent
      hostNetwork: true
      hostPID: true
      hostIPC: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      containers:
        - name: qualys-agent-installer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN", "SYS_CHROOT", "SYS_MODULE"]
          command: ["/bin/bash", "-c", "/entrypoint.sh"]
          env:
            - name: ACTIVATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.activationIdSecret }}
                  key: ACTIVATION_ID
            - name: CUSTOMER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.customerIdSecret }}
                  key: CUSTOMER_ID
            - name: SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMap }}
                  key: SERVER_URI
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMap }}
                  key: LOG_LEVEL
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: host-root
              mountPath: /host
              mountPropagation: HostToContainer
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-sys
              mountPath: /host/sys
              readOnly: true
            - name: host-dev
              mountPath: /host/dev
            - name: host-run
              mountPath: /host/run
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "ps aux | grep -v grep | grep sleep"
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "chroot /host systemctl is-active qualys-cloud-agent"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
            type: Directory
        - name: host-run
          hostPath:
            path: /run
            type: Directory
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
